
"""
Django settings for olive_cafe project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = 'django-insecure-6$cm2ye3-r^i%)73lzyeyso#l9f(*grium$393vq&ej^()=&2q'

DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Jazzmin - Admin Theme
    'jazzmin',

    # Django Default Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'products',
    # 'home',
    'home.apps.HomeConfig',

]


# ============================================================
# JAZZMIN SETTINGS
# ============================================================

JAZZMIN_SETTINGS = {

    # Browser tab title
    "site_title": "Olive Cafe Admin",

    # Admin header
    "site_header": "Olive Cafe",

    # Brand name
    "site_brand": "Olive Cafe",

    # Login page welcome text
    "welcome_sign": "Welcome to Olive Cafe Admin",

    # Footer
    "copyright": "Olive Cafe",

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,

    # Top menu
    "topmenu_links": [

        {
            "name": "Dashboard",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },

        {
            "name": "View Website",
            "url": "/",
            "new_window": True,
        },

    ],

    # User menu
    "usermenu_links": [

        {
            "name": "Olive Cafe Website",
            "url": "/",
            "new_window": True,
        },

    ],

    # Enable Jazzmin UI Builder
    "show_ui_builder": True,

}


# ============================================================
# JAZZMIN UI CUSTOMIZATION
# ============================================================

JAZZMIN_UI_TWEAKS = {

    # Main theme
    "theme": "default",

    # Dark mode theme
    "dark_mode_theme": "darkly",

    # Fixed navigation
    "navbar_fixed": True,
    "sidebar_fixed": True,

    # Sidebar style
    "sidebar_nav_flat_style": True,

    # Button styles
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },

}


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'olive_cafe.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'home' / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'olive_cafe.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'


# ============================================================
# MEDIA FILES
# ============================================================

# Product images and other uploaded files
MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'olivecafe5251@gmail.com'
EMAIL_HOST_PASSWORD = 'ifhkavlbofidcfor'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
