# Generated by Django 6.1.1 on 2026-10-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='message',
            new_name='special_request',
        ),
    ]
